test using reusable workflow

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -3,61 +3,25 @@ name: Test
 on: [ push, pull_request ]
 
 jobs:
-    Consistency:
-        name: 'Consistency'
-        runs-on: ubuntu-latest
-        steps:
-            -   name: Checkout
-                uses: actions/checkout@v2
-
-            -   name: Composer Cache Vars
-                id: composer-cache-vars
-                run: |
-                    echo "::set-output name=dir::$(composer config cache-files-dir)"
-                    echo "::set-output name=timestamp::$(date +"%s")"
-
-            -   name: Cache Composer dependencies
-                uses: actions/cache@v2
-                with:
-                    path: ${{ steps.composer-cache-vars.outputs.dir }}
-                    key: ${{ runner.os }}-composer-^11.5.3-stable-7.4-${{ steps.composer-cache-vars.outputs.timestamp }}
-                    restore-keys: |
-                        ${{ runner.os }}-composer-^11.5.3-stable-7.4-
-                        ${{ runner.os }}-composer-^11.5.3-stable-
-                        ${{ runner.os }}-composer-^11.5.3-
-                        ${{ runner.os }}-composer-
-
-            -   name: Set up PHP Version 7.4
-                uses: shivammathur/setup-php@v2
-                with:
-                    php-version: 7.4
-                    tools: composer:v2
-                    coverage: none
-
-            -   name: "Extract tag, branch, version from GITHUB_REF"
-                id: "github-ref"
-                run: |
-                    echo "::set-output name=tag::$(echo $GITHUB_REF | sed -E -n 's#^refs/tags/(.*)$#\1#p')"
-                    echo "::set-output name=branch::$(echo $GITHUB_REF | sed -E -n 's#^refs/heads/(.*)$#\1#p')"
-                    echo "::set-output name=version::$(echo $GITHUB_REF | sed -E -n 's#^refs/tags/v?([0-9]+\.)([0-9]+\.)([0-9]+)#\1\2\3#p')"
-
-            -   name: Compare tag version with committed version
-                if: steps.github-ref.outputs.version != ''
-                run: |
-                    composer set-version $(echo ${{ steps.github-ref.outputs.tag }} | sed s/^v//g)
-                    test -z "$(git diff --shortstat 2> /dev/null | tail -n1)";
-
-            -   name: Compare extension composer.json with main composer.json
-                run: |
-                    composer extension-verify-composer-json
-
-            -   name: Build extension artifact
-                run: |
-                    composer extension-release
 
     Tests:
-        name: 'T3 ${{ matrix.typo3 }} - PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}'
-        runs-on: ubuntu-18.04
+        uses: 'TYPO3-Console/TYPO3-Console/.github/workflows/TYPO3Build.yml@develop'
+
+        with:
+            name: 'T3 ${{ matrix.typo3 }} - PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}'
+            typo3: '${{ matrix.typo3 }}'
+            php: '${{ matrix.php }}'
+            dependency-version: '${{ matrix.dependency-version }}'
+            experimental: '${{ matrix.experimental }}'
+            uses-db: true
+            pre-install: 'echo pre-install done'
+            post-install: 'echo post-install done'
+            lint: '.Build/bin/parallel-lint --exclude .Build .'
+            test: |
+                echo 'before test'
+                .Build/bin/phpunit
+                echo 'after test'
+            experimental-test: '.Build/bin/phpunit || true'
 
         strategy:
             fail-fast: false
@@ -78,66 +42,18 @@ jobs:
 
         continue-on-error: ${{ matrix.experimental }}
 
-        steps:
-            -   name: Start database server
-                run: sudo /etc/init.d/mysql start
-
-            -   name: Checkout
-                uses: actions/checkout@v2
-
-            -   name: Composer Cache Vars
-                id: composer-cache-vars
-                run: |
-                    echo "::set-output name=dir::$(composer config cache-files-dir)"
-                    echo "::set-output name=timestamp::$(date +"%s")"
-
-            -   name: Cache Composer dependencies
-                uses: actions/cache@v2
-                with:
-                    path: ${{ steps.composer-cache-vars.outputs.dir }}
-                    key: ${{ runner.os }}-composer-${{ matrix.typo3 }}-${{ matrix.dependency-version }}-${{ matrix.php }}-${{ steps.composer-cache-vars.outputs.timestamp }}
-                    restore-keys: |
-                        ${{ runner.os }}-composer-${{ matrix.typo3 }}-${{ matrix.dependency-version }}-${{ matrix.php }}-
-                        ${{ runner.os }}-composer-${{ matrix.typo3 }}-${{ matrix.dependency-version }}-
-                        ${{ runner.os }}-composer-${{ matrix.typo3 }}-
-                        ${{ runner.os }}-composer-
-
-            -   name: Set up PHP Version ${{ matrix.php }}
-                uses: shivammathur/setup-php@v2
-                with:
-                    php-version: ${{ matrix.php }}
-                    tools: composer:v2
-                    coverage: none
-
-            -   name: Environment Check
-                run: |
-                    php --version
-                    composer --version
-
-            -   name: Validate composer.json and composer.lock
-                run: composer validate
-
-            -   name: Install
-                run: |
-                    export COMPOSER_ROOT_VERSION=7.0.4
-                    composer update --with "typo3/cms-core:${{ matrix.typo3 }}" --prefer-${{ matrix.dependency-version }} --prefer-dist --no-interaction
-                    git checkout composer.json
-
-            -   name: Lint
-                run: .Build/bin/parallel-lint --exclude .Build .
-
-            # This fails when command reference is not up to date
-            -   name: Test Command Reference
-                run: |
-                    ./typo3cms commandreference:render > /dev/null 2>&1 && test -z "$(git diff --shortstat 2> /dev/null | tail -n1)"
-
-            -   name: Test Install
-                run: './typo3cms install:setup --database-host-name=127.0.0.1 --database-user-name=root --database-user-password=root --database-name=typo3_test_ci_github  --admin-user-name=admin --admin-password=password --no-interaction -vvv'
-
-            -   name: Test
-                if: '!matrix.experimental'
-                run: .Build/bin/phpunit
-
-            -   name: Test allow failure
-                if: 'matrix.experimental'
-                run: .Build/bin/phpunit || true
+#            # This fails when command reference is not up to date
+#            -   name: Test Command Reference
+#                run: |
+#                    ./typo3cms commandreference:render > /dev/null 2>&1 && test -z "$(git diff --shortstat 2> /dev/null | tail -n1)"
+#
+#            -   name: Test Install
+#                run: './typo3cms install:setup --database-host-name=127.0.0.1 --database-user-name=root --database-user-password=root --database-name=typo3_test_ci_github  --admin-user-name=admin --admin-password=password --no-interaction -vvv'
+#
+#            -   name: Test
+#                if: '!matrix.experimental'
+#                run: .Build/bin/phpunit
+#
+#            -   name: Test allow failure
+#                if: 'matrix.experimental'
+#                run: .Build/bin/phpunit || true
